 function code2EmojiPath(unicode) {
    var emojiImgPath = "./js/chatdemo/emoji/";
    return emojiImgPath + unicode + '.png';
};

function code2Unicode(code, emojiItems){
    for(var i = 0; i < emojiItems.length; i++){
        if(emojiItems[i].code == code){
            return emojiItems[i].unicode
        }
    }    
};

const EmojiItems = (function() {
    return [{
        unicode: '1f600',
        code: "\uD83D\uDE00"
    }, {
        unicode: '1f601',
        code: "\uD83D\uDE01"
    }, {
        unicode: '1f602',
        code: "\uD83D\uDE02"
    }, {
        unicode: '1f603',
        code: "\uD83D\uDE03"
    }, {
        unicode: '1f604',
        code: "\uD83D\uDE04"
    }, {
        unicode: '1f605',
        code: "\uD83D\uDE05"
    }, {
        unicode: '1f606',
        code: "\uD83D\uDE06"
    }, {
        unicode: '1f607',
        code: "\uD83D\uDE07"
    }, {
        unicode: '1f608',
        code: "\uD83D\uDE08"
    }, {
        unicode: '1f609',
        code: "\uD83D\uDE09"
    }, {
        unicode: '1f60a',
        code: "\uD83D\uDE0A"
    }, {
        unicode: '1f60b',
        code: "\uD83D\uDE0B"
    }, {
        unicode: '1f60c',
        code: "\uD83D\uDE0C"
    }, {
        unicode: '1f60d',
        code: "\uD83D\uDE0D"
    }, {
        unicode: '1f60e',
        code: "\uD83D\uDE0E"
    }, {
        unicode: '1f60f',
        code: "\uD83D\uDE0F"
    }].concat([{
            unicode: '1f610',
            code: "\uD83D\uDE10"
        }, {
            unicode: '1f611',
            code: "\uD83D\uDE11"
        }, {
            unicode: '1f612',
            code: "\uD83D\uDE12"
        }, {
            unicode: '1f613',
            code: "\uD83D\uDE13"
        }, {
            unicode: '1f614',
            code: "\uD83D\uDE14"
        }, {
            unicode: '1f615',
            code: "\uD83D\uDE15"
        }, {
            unicode: '1f616',
            code: "\uD83D\uDE16"
        }, {
            unicode: '1f617',
            code: "\uD83D\uDE17"
        }, {
            unicode: '1f618',
            code: "\uD83D\uDE18"
        }, {
            unicode: '1f619',
            code: "\uD83D\uDE19"
        }, {
            unicode: '1f61a',
            code: "\uD83D\uDE1A"
        }, {
            unicode: '1f61b',
            code: "\uD83D\uDE1B"
        }, {
            unicode: '1f61c',
            code: "\uD83D\uDE1C"
        }, {
            unicode: '1f61d',
            code: "\uD83D\uDE1D"
        }, {
            unicode: '1f61e',
            code: "\uD83D\uDE1E"
        }, {
            unicode: '1f61f',
            code: "\uD83D\uDE1F"
        }]).concat([{
            unicode: '1f620',
            code: "\uD83D\uDE20"
        }, {
            unicode: '1f621',
            code: "\uD83D\uDE21"
        }, {
            unicode: '1f622',
            code: "\uD83D\uDE22"
        }, {
            unicode: '1f623',
            code: "\uD83D\uDE23"
        }, {
            unicode: '1f624',
            code: "\uD83D\uDE24"
        }, {
            unicode: '1f625',
            code: "\uD83D\uDE25"
        }, {
            unicode: '1f626',
            code: "\uD83D\uDE26"
        }, {
            unicode: '1f627',
            code: "\uD83D\uDE27"
        }, {
            unicode: '1f628',
            code: "\uD83D\uDE28"
        }, {
            unicode: '1f629',
            code: "\uD83D\uDE29"
        }, {
            unicode: '1f62a',
            code: "\uD83D\uDE2A"
        }, {
            unicode: '1f62b',
            code: "\uD83D\uDE2B"
        }, {
            unicode: '1f62c',
            code: "\uD83D\uDE2C"
        }, {
            unicode: '1f62d',
            code: "\uD83D\uDE2D"
        }, {
            unicode: '1f62e',
            code: "\uD83D\uDE2E"
        }, {
            unicode: '1f62f',
            code: "\uD83D\uDE2F"
        }]).concat([{
            unicode: '1f630',
            code: "\uD83D\uDE30"
        }, {
            unicode: '1f631',
            code: "\uD83D\uDE31"
        }, {
            unicode: '1f632',
            code: "\uD83D\uDE32"
        }, {
            unicode: '1f633',
            code: "\uD83D\uDE33"
        }, {
            unicode: '1f634',
            code: "\uD83D\uDE34"
        }, {
            unicode: '1f635',
            code: "\uD83D\uDE35"
        }, {
            unicode: '1f636',
            code: "\uD83D\uDE36"
        }, {
            unicode: '1f637',
            code: "\uD83D\uDE37"
        }, {
            unicode: '1f638',
            code: "\uD83D\uDE38"
        }, {
            unicode: '1f639',
            code: "\uD83D\uDE39"
        }, {
            unicode: '1f63a',
            code: "\uD83D\uDE3A"
        }, {
            unicode: '1f63b',
            code: "\uD83D\uDE3B"
        }, {
            unicode: '1f63c',
            code: "\uD83D\uDE3C"
        }, {
            unicode: '1f63d',
            code: "\uD83D\uDE3D"
        }, {
            unicode: '1f63e',
            code: "\uD83D\uDE3E"
        }, {
            unicode: '1f63f',
            code: "\uD83D\uDE3F"
        }]);
})();